version: '3'
services:
  db:
    env_file: ./.env
    image: postgres
    ports:
      - "15432:5432"
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_USERNAME=${DB_USERNAME}"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    env_file: ./.env
    build: .
    volumes:
      - .:/memotter
      - tmp-data:/memotter/tmp
      - public-data:/memotter/public
    ports:
      - "3000:3000"
    environment:
      - "RAILS_ENV=${RAILS_ENV}"
    depends_on:
      - db
volumes:
  db-data:
    external: true
  tmp-data:
    external: true
  public-data:
    external: true
